{
 "title": "AppDynamics Kubernetes Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "Service",
    "query": {}
   },
   {
    "name": "Pod",
    "label": "Pods",
    "query": {}
   },
   {
    "name": "Container",
    "label": "Container",
    "query": {}
   },
   {
    "name": "Source",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pod Status    : $Cluster",
   "type": "stat",
   "description": "Number of pods by status. Click the value to open AppDynamics Cloud UI.",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH `Critical/Warning`: count from entities (k8s:cluster) [attributes(k8s.cluster.name) = '$Cluster'].out.to(k8s:namespace).out.to(k8s:pod)[attributes(status) in [2,3]] SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    },
    {
     "constant": 6.5,
     "queryText": "FETCH Unknown: count from entities (k8s:cluster) [attributes(k8s.cluster.name) = '$Cluster'].out.to(k8s:namespace).out.to(k8s:pod)[attributes(status) in [1,null]] SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    },
    {
     "constant": 6.5,
     "queryText": "FETCH `Normal/Healthy`: count from entities (k8s:cluster) [attributes(k8s.cluster.name) = '$Cluster'].out.to(k8s:namespace).out.to(k8s:pod)[attributes(status) in [0]] SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Pod Count by Status : $Cluster",
   "type": "barchart",
   "description": "Number of pods by status over the selected time period.",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH              Running: s.metrics(`k8s:pods.running`, `sys:derived`){timestamp, value},              \nPending: s.metrics(`k8s:pods.pending`, `sys:derived`){timestamp, value},            \nFailed:   s.metrics(`k8s:pods.failed`, `sys:derived`){timestamp, value},       \nSucceeded:       s.metrics(`k8s:pods.succeeded`, `sys:derived`){timestamp, value},        \nUnknown:      s.metrics(`k8s:pods.unknown`, `sys:derived`){timestamp, value}        \n  FROM              s: entities(k8s:cluster) [attributes(`k8s.cluster.name`) ='$Cluster' ]     \nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "type": "text",
   "description": "Navigate to AppDynamics Cloud UI.",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 7 },
   "options": {
    "content": "<br/>\n<a href=\"${Source}/ui/observe/k8s/pod?filter=attributes(status) in [0,1, null,2,3]%26%26%20attributes(k8s.cluster.name)%3D${Cluster:singlequote}&since=${__from}&until=${__to}\" target=\"_blank\">\n  <div style=\"display:flex;justify-content:center;align-items:center\">\n    <img src=\"./public/plugins/appdynamicscloud/img/logo.svg\" width='48' height='48' alt=\"AppDynamicsLogo\" />\n    <h3 style=\"font-size:26px;padding-left:10px;font-weight:bold;margin-bottom: 0;\">Click here to view more <br/> on \n    AppDynamics Cloud<h3>\n  </div>\n</a>"
   }
  },
  { "title": "Pods Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "$Pod",
   "type": "gauge",
   "description": "Mean CPU usage for the selected pods over the selected time period.",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH    `CPU Utilization : ` : metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, value} * metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, group_count} / metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, count} FROM  entities(k8s:pod) [attributes(k8s.pod.name) in [  ${Pod:singlequote} ] ] SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Pod CPU Usage: $Pod",
   "type": "timeseries",
   "description": "CPU usage trend for the selected pods over the selected time period.",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 12 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH  attributes(k8s.pod.name),   `CPU Utilization : ` : metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, value} * metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, group_count} / metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, count} FROM  entities(k8s:pod) [attributes(k8s.pod.name) in [  ${Pod:singlequote} ]] SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Pod CPU Usage Vs Request (%):  $Pod",
   "type": "timeseries",
   "description": "CPU usage per Request Rate for the selected pods over the selected time period.",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\nattributes(k8s.pod.name),\n`Pos CPU Usage Vs Requests :` : (s.metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, value} * s.metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, group_count} * s.metrics(`k8s:cpu.requests`, `infra-agent`) {timestamp, count}*100)/ (s.metrics(`k8s:cpu.requests`, `infra-agent`){timestamp, value} * s.metrics(`k8s:cpu.requests`, `infra-agent`){timestamp, group_count} * s.metrics(`k8s:cpu.usage`, `sys:derived`){timestamp, count})\nFROM   s: entities(k8s:pod) [attributes(k8s.pod.name) in [${Pod:singlequote}]]\nSINCE $__from UNTIL $__to\nLIMITS metrics.round(3)",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "$Pod",
   "type": "stat",
   "description": "Average Memory usage for the selected pods over the selected time period.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\nattributes(k8s.pod.name),\n`Memory Usage : ` :  s.metrics(`k8s:memory.usage`, `sys:derived`){timestamp, value} * s.metrics(`k8s:memory.usage`, `sys:derived`){timestamp, group_count} / (s.metrics(`k8s:memory.usage`, `sys:derived`){timestamp, count} )\nFROM   s: entities(k8s:pod) [attributes(k8s.pod.name) in [  ${Pod:singlequote} ]]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Pod Memory Usage: $Pod",
   "type": "timeseries",
   "description": "Memory usage for the selected pods over the selected time period.",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\nattributes(k8s.pod.name),\n`Memory Usage : ` :  s.metrics(`k8s:memory.usage`, `sys:derived`){timestamp, value} * s.metrics(`k8s:memory.usage`, `sys:derived`){timestamp, group_count} / (s.metrics(`k8s:memory.usage`, `sys:derived`){timestamp, count} )\nFROM   s: entities(k8s:pod) [attributes(k8s.pod.name) in [  ${Pod:singlequote} ]]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  { "title": "Containers Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Container CPU Utilization (%): $Container",
   "type": "timeseries",
   "description": "CPU usage for the selected Containers over the selected time period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n attributes(container.name),\n `CPU Used Utilization : ` : a1.metrics(`infra:container.cpu.used.utilization`, `infra-agent`){timestamp, value} \nFROM a1: entities(infra:container)[attributes(container.name) IN [${Container:singlequote}] && attributes(k8s.pod.name) IN [${Pod:singlequote}] ] \nSINCE $__from UNTIL $__to \nLIMITS metrics.round(3)",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Container CPU Throttled Time (seconds): $Container",
   "type": "timeseries",
   "description": "CPU Throttled Time in seconds for the selected Containers over the selected time period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n attributes(container.name),\n `CPU Throttled Time : ` : a1.metrics(`infra:container.cpu.throttled_time`, `infra-agent`){timestamp, value}\nFROM a1: entities(infra:container)[attributes(container.name) IN [${Container:singlequote}] && attributes(k8s.pod.name) IN [${Pod:singlequote}] ] \nSINCE $__from UNTIL $__to ",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Container File System read-write IO/second: $Container",
   "type": "timeseries",
   "description": "File system read/wirte I/O (per second) for the selected Containers over the selected time period.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n attributes(container.name),\n `Filesystem Read : ` : a1.metrics(\"infra:container.filesystem.read.io_sec\", \"infra-agent\"){timestamp, value} / 1024,\n `Filesystem Write : ` : a1.metrics(\"infra:container.filesystem.write.io_sec\", \"infra-agent\"){timestamp, value} / 1024\nFROM a1: entities(infra:container)[attributes(container.name) IN [${Container:singlequote}] && attributes(k8s.pod.name) IN [${Pod:singlequote}] ] \nSINCE $__from UNTIL $__to ",
     "queryTypeSelected": "querybox"
    }
   ]
  }
 ]
}