{
 "title": "AppDynamics APM Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ServiceName",
    "label": "Service Name",
    "query": {}
   },
   {
    "name": "InstanceStatus",
    "query": "Critical : 3, Warning : 2, Normal/Healthy : 0, Unknown : 1\\,null"
   },
   {
    "name": "ServiceInstance",
    "label": "Service Instances",
    "query": {}
   },
   {
    "name": "Source",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Service Instances",
   "type": "stat",
   "description": "Service instances count by status for the selected services. Click the value to open AppDynamics Cloud UI.",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "fetch  Normal: count from entities(apm:service) [ attributes(service.name) IN [${ServiceName:singlequote} ]].out.to(apm:service_instance) [attributes(status) = 0 ]",
     "queryTypeSelected": "querybox"
    },
    {
     "constant": 6.5,
     "queryText": "fetch  Critical: count from entities(apm:service) [attributes(service.name) IN [${ServiceName:singlequote} ]] .out.to(apm:service_instance) [attributes(status) = 3]",
     "queryTypeSelected": "querybox"
    },
    {
     "constant": 6.5,
     "queryText": "fetch  Warning : count from entities(apm:service) [ attributes(service.name) IN [${ServiceName:singlequote} ]] .out.to(apm:service_instance)  [attributes(status) = 2]",
     "queryTypeSelected": "querybox"
    },
    {
     "constant": 6.5,
     "queryText": "fetch  Unknown: count from entities(apm:service) [ attributes(service.name) IN [${ServiceName:singlequote} ]] .out.to(apm:service_instance)  [attributes(status) IN [1,null]]",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Average Response Time: $ServiceInstance",
   "type": "timeseries",
   "description": "Average Response Time for the selected service instances over the selected time period. ",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH   attributes(service.instance.id),   `Avg Response Time :` : metrics(apm:response_time, `sys:derived`) \nFROM   entities(apm:service) [ attributes(service.name) IN [${ServiceName:singlequote}]] .out.to(apm:service_instance) [ attributes(service.instance.id)  in [ ${ServiceInstance:singlequote}] ] SINCE $__from UNTIL $__to ",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "type": "text",
   "description": "Navigate to AppDynamics Cloud UI.",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 6 },
   "options": {
    "content": "<br/>\n<a href=\"${Source}/ui/observe/apm/service_instance?filter=attributes(status) IN [${InstanceStatus:raw}]%26%26%20attributes(service.name) IN [${ServiceName:singlequote}]&since=${__from}&until=${__to}\" target=\"_blank\">\n  <div style=\"display:flex;justify-content:center;align-items: center;\">\n    <img src=\"./public/plugins/appdynamicscloud/img/logo.svg\" width='48' height='48' alt=\"AppDynamicsLogo\" />\n    <h3 style=\"margin-bottom:0;font-size:28px;padding-left:10px;font-weight:bold\">Click here to view more <br/> on \n    AppDynamics Cloud<h3>\n  </div>\n</a> "
   }
  },
  {
   "title": "$ServiceInstance",
   "type": "stat",
   "description": "Mean Number of calls per minute from the selected service instances over the selected time period. ",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH    `Calls per min :` : metrics(apm:calls_min, `sys:derived`) FROM   entities(apm:service) [ attributes(service.name) in [${ServiceName:singlequote}]] .out.to(apm:service_instance) [ attributes(service.instance.id)  in [ ${ServiceInstance:singlequote}] ]  SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Calls per min: $ServiceInstance",
   "type": "timeseries",
   "description": "Number of calls per minute from the selected service instances over the selected time period. ",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 10 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH   attributes(service.instance.id),   `Calls per min :` : metrics(apm:calls_min, `sys:derived`) FROM   entities(apm:service) [ attributes(service.name) in [${ServiceName:singlequote}]] .out.to(apm:service_instance) [ attributes(service.instance.id)  in [ ${ServiceInstance:singlequote}] ]  SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "$ServiceInstance",
   "type": "stat",
   "description": "Total Number of errors per minute for the selected services.",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH     `Errors per min :` : metrics(apm:errors_min, `sys:derived`) FROM   entities(apm:service) [ attributes(service.name) in [${ServiceName:singlequote}]] .out.to(apm:service_instance) [ attributes(service.instance.id)  in [ ${ServiceInstance:singlequote}] ]  SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Errors per min: $ServiceInstance",
   "type": "timeseries",
   "description": "Number of Errors per minute for the selected service instances over the selected time period. ",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 17 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH   attributes(service.instance.id),   `Errors per min :` : metrics(apm:errors_min, `sys:derived`) FROM   entities(apm:service) [ attributes(service.name) in [${ServiceName:singlequote}]] .out.to(apm:service_instance) [ attributes(service.instance.id)  in [ ${ServiceInstance:singlequote}] ]  SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Incoming Calls to Service Instance: $ServiceInstance",
   "type": "table",
   "description": "Detailed metrics of the incoming calls from the selected service instances.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "SINCE $__from UNTIL $__to FROM a30: entities(apm:service_instance) [attributes(service.instance.id)in [${ServiceInstance:singlequote}]]  .in(common:interaction_to).from[attributes(`interaction.context.id`) = ''].out(common:interaction_from).to(apm:service) FETCH Status: attributes(status),  Source: a30.attributes(service.name), `Avg Response Time`: a30.metrics(apm:response_time,`sys:derived`).value/1000000,  `Calls/min`: a30.metrics(apm:calls_min,`sys:derived`).value,  `Errors/min`: a30.metrics(apm:errors_min,`sys:derived`).value LIMITS metrics.round(2)",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Outgoing Calls from Service Instance: $ServiceInstance",
   "type": "table",
   "description": "Detailed metrics of the outgoing calls from the selected service instances.",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 24 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FROM a55: entities(apm:service_instance)[attributes(service.instance.id) in [ ${ServiceInstance:singlequote}]].in(common:interaction_from).from[attributes(`interaction.context.id`) = ''].out(common:interaction_to).to(apm:backend)\nFETCH\nStatus: a55.attributes(status) ,\n`Destination` : a55.attributes(backend.name),\n`Avg Response Time` :  a55.metrics(apm:response_time, `APM`).value / 1000000,\n `Calls/min`:  a55.metrics(apm:calls_min, `APM`).value,\n `Errors/min`:  a55.metrics(apm:errors_min, `APM`).value\nLIMITS metrics.round(2), topology.count(1000)\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    },
    {
     "constant": 6.5,
     "queryText": "FROM a52: entities(apm:service_instance)[attributes(service.instance.id) in [ ${ServiceInstance:singlequote}]].in(common:interaction_from).from[attributes(`interaction.context.id`) = ''].out(common:interaction_to).to(apm:service)\n FETCH Status: a52.attributes(status),\n`Destination` :  a52.attributes(service.name), `Avg Response Time` : a52.metrics(apm:response_time, `sys:derived`).value / 1000000,  `Calls/min`:  a52.metrics(apm:calls_min, `sys:derived`).value,  `Errors/min`: a52.metrics(apm:errors_min, `sys:derived`).value LIMITS metrics.round(2), topology.count(1000)\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  }
 ]
}