{
 "title": "AWS Host Details",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Status",
    "label": "Status",
    "query": "Critical : 3, Warning : 2, Normal/Healthy  : 0, Unknown : 1\\,null"
   },
   {
    "name": "HostId",
    "label": "Host ID",
    "query": {}
   },
   {
    "name": "Source",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "description": "Navigate to AppDynamics Cloud UI.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "<br/>\n<a href=\"${Source}/ui/observe/aws/ec2?filter=attributes(status) IN [${Status:raw}]%26%26%20attributes(host.id) IN [${HostId:singlequote}]&since=${__from}&until=${__to}\" target=\"_blank\">\n  <div style=\"display:flex;justify-content:center;align-items: center;\">\n    <img src=\"./public/plugins/appdynamicscloud/img/logo.svg\" width='32' height='32' alt=\"AppDynamicsLogo\" />\n    <h3 style=\"margin-bottom:0;font-size:28px;padding-left:10px;font-weight:bold\">Click here to view more <br/> on \n    AppDynamics Cloud<h3>\n  </div>\n</a> "
   }
  },
  {
   "title": "CPU Utilization % - ${HostId}",
   "type": "timeseries",
   "description": "CPU Utilization(%) for the selected hosts over the selected time period.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n`Host Id` : attributes(host.id),\n`CPU Utilization % `: s.metrics(`infra:system.cpu.used.utilization`, `aws-cloudwatch`)\n        FROM\n            s: entities(aws:ec2) [attributes(host.id) in [${HostId:singlequote}]]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "CPU Credits - ${HostId}",
   "type": "timeseries",
   "description": "Used vs Balance CPU Credits for the selected hosts over the selected time period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n`Host Id` : attributes(host.id),\n`CPU Used Credits :`: s.metrics(`cloud:system.cpu.used.credits`, `aws-cloudwatch`),\n`CPU Balance Credits :`: s.metrics(`cloud:system.cpu.balance.credits`, `aws-cloudwatch`)\n        FROM\n            s: entities(aws:ec2) [attributes(host.id) in [${HostId:singlequote}]]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Disk Throughput (KiB/sec) - ${HostId}",
   "type": "timeseries",
   "description": "Disk Throughput for the selected hosts over the selected time period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n`Host Id` : attributes(host.id),\n`Disk Read KiB/sec`: s.metrics(`infra:system.disk.read.io_sec`, `aws-cloudwatch`) / 1024\n        FROM\n            s: entities(aws:ec2) [attributes(host.id) in [${HostId:singlequote}]]\n LIMITS metrics.granularityDuration(PT5M), metrics.round(3) SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    },
    {
     "constant": 6.5,
     "queryText": "FETCH\n`Host Id` : attributes(host.id),\n`Disk Written KiB/sec`: s.metrics(`infra:system.disk.write.io_sec`, `aws-cloudwatch`) / 1024\n        FROM\n            s: entities(aws:ec2) [attributes(host.id) in [${HostId:singlequote}]]\n LIMITS metrics.granularityDuration(PT5M), metrics.round(3) SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Disk IOPS (Ops/Sec) - ${HostId}",
   "type": "timeseries",
   "description": "Disk IOPS - Operations per seconds on the selected hosts over the selected time period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n`Host Id` : attributes(host.id),\n`Disk Reads Ops/sec`:            s.metrics(`infra:system.disk.read.operations_sec`, `aws-cloudwatch`),\n`Disk Writes Ops/sec`:             s.metrics(`infra:system.disk.write.operations_sec`, `aws-cloudwatch`)\n        FROM\n            s: entities(aws:ec2) [attributes(host.id) in [${HostId:singlequote}]]\n LIMITS metrics.granularityDuration(PT5M), metrics.round(3) SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Network Throughput (KiB/sec) - ${HostId}",
   "type": "timeseries",
   "description": "Network Throughput in KiB per seconds for the selected hosts over the selected time period.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n`Host Id` : attributes(host.id),\n`Network IO Incoming KiB/sec :`: s.metrics(`infra:system.network.receive.io_sec`, `aws-cloudwatch`)/ 1024,\n`Network IO Outgoing KiB/sec :`: s.metrics(`infra:system.network.transmit.io_sec`, `aws-cloudwatch`) / 1024\n        FROM\n            s: entities(aws:ec2) [attributes(host.id) in [${HostId:singlequote}]]\n LIMITS metrics.granularityDuration(PT5M), metrics.round(3) SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Network Packets (Count/sec) - ${HostId}",
   "type": "timeseries",
   "description": "Number of Network Packets per seconds from the selected hosts over the selected time period.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH\n`Host Id` : attributes(host.id),\n`Network Incoming Packets/sec`:            s.metrics(`infra:system.network.receive.packets_sec`, `aws-cloudwatch`),\n`Network Outgoing Packets/sec`:             s.metrics(`infra:system.network.transmit.packets_sec`, `aws-cloudwatch`)\n        FROM\n            s: entities(aws:ec2) [attributes(host.id) in [${HostId:singlequote}]]\n LIMITS metrics.granularityDuration(PT5M), metrics.round(3) SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Status Check Failed (0/1) - ${HostId}",
   "type": "timeseries",
   "description": "Status Check Failed value for the selected hosts over the selected time period.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH `Host Id` : attributes(host.id), `Status Check Failed 0/1 :`: s.metrics('aws:ec2.status_check.failure', 'aws-cloudwatch') FROM s: entities(aws:ec2) [attributes(host.id) in [${HostId:singlequote}]] LIMITS metrics.round(3) SINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  }
 ]
}