{
 "title": "AWS Host Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Status",
    "label": "Status",
    "query": "Critical : 3, Warning : 2, Normal/Healthy : 0, Unknown : 1\\,null"
   },
   {
    "name": "Source",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Total Hosts",
   "type": "stat",
   "description": "Total number of AWS hosts. Click the value to open AppDynamics Cloud UI.",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "FETCH \n`Total Hosts - Click the value to open AppDynamics Cloud UI`: count\n FROM\ns: entities(aws:ec2)\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "description": "Total number of AWS hosts with Critical status. Click the value to open AppDynamics Cloud UI.",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "fetch `Critical AWS Hosts - Click the value to open AppDynamics Cloud UI`: count\nfrom\ns: entities(aws:ec2) [attributes(`status`) in [3] ]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "description": "Total number of AWS hosts with Warning status. Click the value to open AppDynamics Cloud UI.",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "fetch `Warning AWS Hosts - Click the value to open AppDynamics Cloud UI`: count\nfrom\ns: entities(aws:ec2) [attributes(`status`) in [2] ]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "stat",
   "description": "Total number of AWS hosts with Unknown status. Click the value to open AppDynamics Cloud UI.",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "fetch `Unknown AWS Hosts - Click the value to open AppDynamics Cloud UI`: count\nfrom\ns: entities(aws:ec2) [attributes(`status`) in [1,null] ]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "title": "Healthy/Normal",
   "type": "stat",
   "description": "Total number of AWS hosts with Normal or Healthy status. Click the value to open AppDynamics Cloud UI.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "fetch `Normal/Healthy AWS Hosts - Click the value to open AppDynamics Cloud UI`: count\nfrom\ns: entities(aws:ec2) [attributes(`status`) in [0] ]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  },
  {
   "type": "text",
   "description": "Navigate to AppDynamics Cloud UI.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "options": {
    "content": "<br/>\n<a href=\"${Source}/ui/observe/aws/ec2?filter=attributes(status) IN [${Status:raw}]&since=${__from}&until=${__to}\" target=\"_blank\">\n  <div style=\"display:flex;justify-content:center;align-items: center;\">\n    <img src=\"./public/plugins/appdynamicscloud/img/logo.svg\" width='48' height='48' alt=\"AppDynamicsLogo\" style=\"margin-top: 80px;\" />\n    <h3 style=\"margin-bottom:0;font-size:28px;padding-left:10px;margin-top:80px;font-weight:bold;vertical-align:center\">Click here to view more <br/> on \n    AppDynamics Cloud<h3>\n  </div>\n</a> "
   }
  },
  {
   "title": "Host Details",
   "type": "table",
   "description": "Host lists with the selected status values. Click Host ID to visit 'AWS Host Details' dashboard for more details.",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 4 },
   "targets": [
    {
     "constant": 6.5,
     "queryText": "fetch \n`Status`:attributes(status),\n`Host ID`:attributes(host.id),\n`Host Name`:attributes(host.display_name),\n`OS`:attributes(os.type),\n`CPU Utilization %`: s.metrics(`infra:system.cpu.used.utilization`, `aws-cloudwatch`).value,\n`Disk Reads Ops/s`: s.metrics(`infra:system.disk.read.operations_sec`, `aws-cloudwatch`).value,\n`Disk Writes Ops/s`: s.metrics(`infra:system.disk.write.operations_sec`, `aws-cloudwatch`).value,\n`Network IO Incoming KiB/s`: s.metrics(`infra:system.network.receive.io_sec`, `aws-cloudwatch`).value/1024,\n`Network IO Outgoing KiB/s`: s.metrics(`infra:system.network.transmit.io_sec`, `aws-cloudwatch`).value/1024\nfrom\ns: entities( aws:ec2) [attributes(`status`) in [ ${Status:raw}] ]\nSINCE $__from UNTIL $__to",
     "queryTypeSelected": "querybox"
    }
   ]
  }
 ]
}