apiVersion: v1
kind: ConfigMap
metadata:
  name: appd-basic-cm
  namespace: default
data:
  grafana.yaml: |-
   {
    "apiVersion": 1,
    "datasources": [
     {
      "editable": true,
      "name": "Appdynamics Cloud",
      "type": "appdynamicscloud",
      "orgId": 1,
      "isDefault":true,
      "jsonData":{
        "authtype":"Basic",
        "clientId":"srv_2FdzxQ9YYnYgFpYBRtddQl",
        "secretKey":"aFw73Ww97n3P_GByFLwqYTdAvN9KmgJ8T_vn3GjomiQ",
        "appdtid":"dfdbdf71-7322-44d0-85fb-36c69a7c3789",
        "url":"https://lab1.observe.appdynamics.com"
       },
      "version": 1,
      }]
    }
