apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: validator-banking-rv
    version: "1"
  name: validator-banking-rv
spec:
  ports:
    - port: 6002
      protocol: TCP
      targetPort: 6002
  selector:
    app: validator-banking-rv
    version: "1"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validator-banking-rv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validator-banking-rv
  template:
    metadata:
      labels:
        app: validator-banking-rv
        version: "1"
      annotations:
        #sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: validator-banking-rv
          command: ["/bin/sh"]
          args: ["-c", "java -jar /app/validatorService-0.0.1-SNAPSHOT.jar"]
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=validator-banking-rv,service.namespace=banking,k8s.namespace.name=banking
            - name: JAVA_OPTS
              value: '-javaagent:/opt/appdynamics/javaagent.jar'
          image: sgioia/cl23-fin-validator:cve1
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
   