apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: approval-banking-rv
    version: "1"
  name: approval-banking-rv
spec:
  ports:
    - port: 5001
      protocol: TCP
      targetPort: 5001
  selector:
    app: approval-banking-rv
    version: "1"
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-banking-rv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: approval-banking-rv
  template:
    metadata:
      labels:
        app: approval-banking-rv
        version: "1"
      annotations:
        #sidecar.opentelemetry.io/inject: "true"
        instrumentation.opentelemetry.io/inject-java: "true"
    spec:
      containers:
        - name: approval-banking-rv
          command: ["/bin/sh"]
          args: ["-c", "java $JAVA_OPTS  -jar /approvalService-0.0.1-SNAPSHOT.jar"]
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=approval-banking-rv,service.namespace=banking,k8s.namespace.name=banking
            - name: JAVA_OPTS
              value: ""
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: fin-app-props
                  key: SPRING.DATASOURCE.URL
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: fin-app-props
                  key: SPRING.DATASOURCE.USERNAME
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: fin-app-props
                  key: SPRING.DATASOURCE.PASSWORD
            - name: SPRING.JPA.HIBERNATE.DDL-AUTO
              valueFrom:
                configMapKeyRef:
                  name: fin-app-props
                  key: SPRING.JPA.HIBERNATE.DDL-AUTO 
          image: sgioia/cl23-fin-approval:3
          imagePullPolicy: Always
          ports:
            - containerPort: 5001