global:
  clusterName: mickey
  oauth:
    clientId: agt_27W0lc5lXSZl1EBjTiZyd2
    clientSecret: twu03GHE_tNlvurxg01XCL2lGzW_3kPetHmavM2lxkA
    endpoint: https://appd-channel.observe.appdynamics.com/data
    tokenUrl: https://appd-channel.observe.appdynamics.com/auth/5bcb9501-4f1f-4f2b-8366-52ace9aa7bb4/default/oauth2/token
  # # If Proxy is needed for agent Management
  # # [Default]
  # agentManagementProxy:
  #   httpProxy: ""
  #   httpsProxy: ""
  #   noProxy: []
  # # [Example]
  # agentManagementProxy:
  #   httpProxy: http://example-proxy.com
  #   httpsProxy: https://example-proxy.com
  #   noProxy:
  #     - http://example-dont-use-for-url1.com
  #     - https://example-dont-use-for-url2.com

appdynamics-cloud-k8s-monitoring:
  install:
    clustermon: true 
    defaultInfraCollectors: true 
    logCollector: false    
  # # Enable disable agent Management for collectors
  # # [Default]
  # agentManagementEnabled:
    # clustermon: true
    # defaultInfraCollectors: true
    # logCollector: true
  # # The name to be used for creating the service account for the cluster collector.
  # # [Default]
  # clustermonServiceAccount: appdynamics-clustermon

  # # The name to be used for creating the service account for the infrastructure collector.
  # # [Default]
  # inframonServiceAccount: appdynamics-inframon

  # Configurations for the cluster collector
  clustermonConfig:
    os: linux

    # # The log level of the collector. (info/debug)
    # # [Default]
    # logLevel: info

    # # The maximum size of one log file (in MB).
    # # [Default]
    # logFilesMaxSizeMb: 10

    # # The maximum number of log files created before overwriting the oldest one.
    # # [Default]
    # logFilesNumBackups: 4

    # # Whether Kubernetes® logs will report logs.
    # # [Default]
    # printToStdout: true

    # # The filters that you can use for monitoring. You can include these filters:
    # # namespace: The namespaces to be monitored.
    # # entity: The entities that are excluded from monitoring.
    # # label: The labels that are excluded from reporting.
    # # annotation: The annotations that are excluded from reporting.
    # # [Default]
    # filters:
    #   namespace:
    #     includeRegex: ".*"
    #     excludeRegex: ""
    #   entity:
    #     excludeRegex: "kube-root-ca.crt|openshift-service-ca.crt"
    #     excludeLabels:
    #   label:
    #     excludeRegex: ""
    #   annotation:
    #     excludeRegex: ""

    # # Configuration override for ingress controller labels and metrics port.
    # # [Default]
    # ingressControllers:
    #   nginx: 
    #     port: 10254
    #     labels: 
    #     app.kubernetes.io/component: controller
    #     app.kubernetes.io/instance: ingress-nginx
    #     app.kubernetes.io/name: ingress-nginx

    # # The events that require collection. You can exclude the required events based on the severity (INFO, WARNING, SEVERE) and Kubernetes event reason.
    # # You can create a custom event group classified as severe events. This classifies the events as severe based on the list of event reasons that you specify in the severeGroupByReason field.
    # # [Default]
    # events:
    #   enabled: true
    #   severityToExclude: []
    #   reasonToExclude: []
    #   severeGroupByReason: []

    # # This allows you to enable or disable monitoring Configurations (ConfigMap, Secret)
    # # [Default]
    # configurations:
    #   enabled: true

  # Configurations for the infrastructure manager (used by cluster collector and infra collectors)
  # infraManagerConfig:
    # # The log level of the infrastructure manager. (info/debug)
    # # [Default]
    # logLevel: info

    # # The maximum size of one log file (in MB).
    # # [Default]
    # logFilesMaxSizeMb: 10

    # # The maximum number of log files created before overwriting the oldest one.
    # # [Default]
    # logFilesNumBackups: 4

    # # Determines whether logs report through Kubernetes logs.
    # # [Default]
    # printToStdout: true

  # Configurations for the container collector
  containermonConfig:
    os:
      - linux

    # # The log level of the collector. (info/debug)
    # # [Default]
    # logLevel: info

    # # The maximum size of one log file (in MB).
    # # [Default]
    # logFilesMaxSizeMb: 10

    # # The maximum number of log files created before overwriting the oldest one.
    # # [Default]
    # logFilesNumBackups: 4

    # # To override the parameters mentioned in this table for a specific operating system.
    # # For example, if you want to set different logLevel for linux and Windows include the following:
    # # [Example]
    # env:
    #   linux:
    #     logLevel: info
    #   windows:
    #     logLevel: debug

  servermonConfig:
    os:
      - linux

    # # The port used to start Node Exporter.
    # # [Default]
    # exporterPort: 9100

    # # The log level of the collector. (info/debug)
    # # [Default]
    # logLevel: info

    # # The maximum size of one log file (in MB).
    # # [Default]
    # logFilesMaxSizeMb: 10

    # # The maximum number of log files created before overwriting the oldest one.
    # # [Default]
    # logFilesNumBackups: 4

    # # To override the parameters mentioned in this table for a specific operating system.
    # # For example, if you want to set different logLevel for linux and Windows include the following:
    # # [Example]
    # env:
    #   linux:
    #     logLevel: info
    #   windows:
    #     logLevel: debug

  # # Properties for the Cluster Collector pod
  # # [Default]
  # clustermonPod:

    # # The cluster collector image address in the format <registryUrl>/<registryAccount>/<project>:<tag>
    # # [Default]
    # image: appdynamics/appdynamics-cloud-k8s-monitoring:<latest-available-tag>

    # # Image pull policy for the Cluster Collector pod.
    # # [Default]
    # imagePullPolicy: Always

    # # PriorityClass assigned to the Cluster Collector pod.
    # # [Default]
    # priorityClassName: null
       
    # # Resources you assign to the Cluster Collector pod.
    # # [Default]
    # resources:
    #   limits:
    #     cpu: 1000m
    #     memory: 1000Mi
    #   requests:
    #     cpu: 500m
    #     memory: 750Mi

    # # Labels for the pod.
    # # [Example]
    # labels:
    #   key1: "value1"
    # # [Default]
    # labels: {}

    # # Annotations for the pod.
    # # [Example]
    # annotations:
    #   key2: "value2"
    # # [Default]
    # annotations: {}

    # # Tolerations for the pod.
    # # [Example]
    # tolerations:
    # - key: "key3"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # # [Default]
    # tolerations: []

    # # Node selector for the pod.
    # # [Example]
    # nodeSelector:
    #   disktype: ssd
    # # [Default (for linux)]
    # nodeSelector:
    #   kubernetes.io/os: linux
    # # [Default (for windows)]
    # nodeSelector:
    #   kubernetes.io/os: windows

    # # Names of any image pull secrets for the pod.
    # # [Example]
    # imagePullSecrets:
    # - name: aws-ecr-secret
    # # [Default]
    # imagePullSecrets: []

    # # Affinity for the pod.
    # # [Example]
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: key4
    #           operator: In
    #           values:
    #           - value3
    #           - value4
    # # [Default]
    # affinity: {}

    # # Security Context for the pod.
    # # [Example]
    # securityContext:
    #   fsGroupChangePolicy: "OnRootMismatch"
    # # [Default]
    # securityContext: {}
  # # Properties for the Infrastructure Collector pod
  # # [Default]
  # inframonPod:

    # # The infrastructure collector image address in the format <registryUrl>/<registryAccount>/<project>:<tag>
    # # [Default]
    # image: appdynamics/appdynamics-cloud-k8s-monitoring:<latest-available-tag>

    # # Image pull policy for the Infrastructure Collector pod.
    # # [Default]
    # imagePullPolicy: Always
    
    # # PriorityClass assigned to the Infrastructure Collector pod.
    # # [Default]
    # priorityClassName: null
    
    # # Resources you assign to the Infrastructure Collector pod.
    # # [Default (for linux)]
    # resources:
    #   limits:
    #     cpu: 350m
    #     memory: 100Mi
    #   requests:
    #     cpu: 200m
    #     memory: 64Mi
    # # [Default (for windows)]
    # resources:
    #   limits:
    #     cpu: 350m
    #     memory: 300Mi
    #   requests:
    #     cpu: 200m
    #     memory: 150Mi

    # # Labels for the pod.
    # # [Example]
    # labels:
    #   key1: "value1"
    # # [Default]
    # labels: {}

    # # Annotations for the pod.
    # # [Example]
    # annotations:
    #   key2: "value2"
    # # [Default]
    # annotations: {}

    # # Tolerations for the pod.
    # # [Example]
    # tolerations:
    # - key: "key3"
    #   operator: "Exists"
    #   effect: "NoSchedule"
    # # [Default]
    # tolerations: []

    # # Node selector for the pod.
    # # [Example]
    # nodeSelector:
    #   disktype: ssd
    # # [Default (for linux)]
    # nodeSelector:
    #   kubernetes.io/os: linux
    # # [Default (for windows)]
    # nodeSelector:
    #   kubernetes.io/os: windows

    # # Names of any image pull secrets for the pod.
    # # [Example]
    # imagePullSecrets:
    # - name: aws-ecr-secret
    # # [Default]
    # imagePullSecrets: []

    # # Affinity for the pod.
    # # [Example]
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #       - matchExpressions:
    #         - key: key4
    #           operator: In
    #           values:
    #           - value3
    #           - value4
    # # [Default]
    # affinity: {}

    # # Security Context for the pod.
    # # [Example]
    # securityContext:
    #   fsGroupChangePolicy: "OnRootMismatch"
    # # [Default]
    # securityContext: {}

    # # To override the parameters mentioned in this table for a specific operating system.
    # # For example, if you want to set different imagePullPolicy for linux and Windows include the following:
    # # [Example]
    # env:
    #   linux:
    #     imagePullPolicy: IfNotPresent
    #   windows:
    #     imagePullPolicy: Never

appdynamics-otel-collector:
  clientId: agt_27W0lc5lXSZl1EBjTiZyd2
  clientSecret: twu03GHE_tNlvurxg01XCL2lGzW_3kPetHmavM2lxkA
  endpoint: https://appd-channel.observe.appdynamics.com/data
  tokenUrl: https://appd-channel.observe.appdynamics.com/auth/5bcb9501-4f1f-4f2b-8366-52ace9aa7bb4/default/oauth2/token
  # This allows you to enable or disable the Network Collector related receiver & processors.
  # Note: This must be enabled along with "appdynamics-network-monitoring.enabled" configuration. 
  enableNetworkMonitoring: true

# Configurations for the Network Collector
appdynamics-network-monitoring:
  enabled: true
  # # The log level of the collector. (error/warning/info/debug/trace)
  # # [Default]
  # log:
  #   level: warning
  
  # # Properties for the Kernel Collector
  # kernelCollector:
    # # This allows you to enable or disable the Kernel Collector portion of the Network Collector.
    # # [Default]
    # enabled: true
  
    # # The Kernel Collector image address in format: <registryAccount>/<project>:<tag>
    # # [Default]
    # image: otel/opentelemetry-ebpf-kernel-collector:v0.10.2
  
    # # Image pull policy for the pod.
    # # [Default]
    # imagePullPolicy: Always
  
    # # Image pull secrets for the pod.
    # # [Default]
    # imagePullSecrets: []
  
    # # Node selector for the pod.
    # # [Default]
    # nodeSelector:
    #   kubernetes.io/arch: amd64
    #   kubernetes.io/os: linux
  
    # # Defines the service account that is created and assigned to the Kernel Collector
    # # [Default]
    # serviceAccount:
    #   create: false
    #   name: ""
  
    # # Tolerations for the pod.
    # # [Default]
    # tolerations:
    # - operator: "Exists"
    #   effect: "NoExecute"
    # - operator: "Exists"
    #   effect: "NoSchedule"
  
    # # Affinity for the pod.
    # # [Default]
    # affinity: {}
  
    # # Resources you assign to the pod.
    # # [Default]
    # resources: {}
  
  # # Properties for the Kubernetes Collector
  # k8sCollector:
    # # This allows you to enable or disable the Kubernetes Collector portion of the Network Collector.
    # # [Default]
    # enabled: true
  
    # # Defines the k8s-relay container in the pod.
    # relay:
      # # The k8s-relay image address in format: <registryAccount>/<project>:<tag>
      # # [Default]
      # image: otel/opentelemetry-ebpf-k8s-relay:v0.10.2
  
      # # Image pull policy for the container.
      # # [Default]
      # imagePullPolicy: Always
      
      # # Resources you assign to the container.
      # # [Default]
      # resources: {}
  
    # # Defines the k8s-watcher container in the pod.
    # watcher:
      # # The k8s-watcher image address in format: <registryAccount>/<project>:<tag>
      # # [Default]
      # image: otel/opentelemetry-ebpf-k8s-watcher:v0.10.2
  
      # # Image pull policy for the container.
      # # [Default]
      # imagePullPolicy: Always
      
      # # Resources you assign to the container.
      # # [Default]
      # resources: {}
  
    # # Image pull secrets for the pod.
    # # [Default]  
    # imagePullSecrets: []
    
    # # Node selector for the pod.
    # # [Default]
    # nodeSelector:
    #   kubernetes.io/arch: amd64
    #   kubernetes.io/os: linux
  
    # # Affinity for the pod.
    # # [Default]
    # affinity: {}
  
    # # Tolerations for the pod.
    # # [Default]
    # tolerations: []
  
    # # Defines the service account that is created and assigned to the Kubernetes Collector
    # # [Default]  
    # serviceAccount:
    #   create: false
    #   name: ""
  
  # # Properties for the Reducer
  # reducer:
    # # Scale the Reducer processing capacity by increasing the number of ingestion shards.
    # # [Default]
    # ingestShards: 1
  
    # # Scale the Reducer processing capacity by increasing the number of matching shards.
    # # [Default]
    # matchingShards: 1
  
    # # Scale the Reducer processing capacity by increasing the number of aggregation shards.
    # # [Default]
    # aggregationShards: 1
  
    # # Disable specific metrics from being generated (applied before any enableMetrics configs).
    # # [Example]
    # disableMetrics:
    # # To disable an entire metric category:
    # - tcp.all
    # # To disable a single metric:
    # - udp.bytes
    # # [Default]
    # disableMetrics:
    # - ebpf_net.all
  
    # # Enable which metrics to be generated (applied after any disableMetrics configs).
    # # [Example]
    # enableMetrics:
    # # To enable an entire metric category:
    # - tcp.all
    # # To enable a single metric:
    # - udp.bytes
    # # [Default]
    # enableMetrics: []
  
    # # Port used to listen for incoming connections from Kernel and Kubernetes Collectors.
    # # [Default]
    # telemetryPort: 7000
  
    # # The Reducer image address in format: <registryAccount>/<project>:<tag>
    # # [Default]
    # image: otel/opentelemetry-ebpf-reducer:v0.10.2
  
    # # Image pull policy for the pod.
    # # [Default]
    # imagePullPolicy: Always
  
    # # Image pull secrets for the pod.
    # # [Default] 
    # imagePullSecrets: []
  
    # # Resources you assign to the pod.
    # # [Default]
    # resources: {}
  
    # # Node selector for the pod.
    # # [Default]
    # nodeSelector:
    #   kubernetes.io/arch: amd64
    #   kubernetes.io/os: linux
  
    # # Affinity for the pod.
    # # [Default]
    # affinity: {}
  
    # # Tolerations for the pod.
    # # [Default]
    # tolerations: []
  
  # # If set to true, a Kubernetes Role is created. The Role is bound to the serviceAccount defined at k8sCollector.serviceAccount.
  # # [Default]
  # rbac:
  #   create: true
